### PR TITLE
Upgrade Shader Editor

### PR DESCRIPTION
**Pull request by Kuranes**
- upgrade to latest codemiror
- upgrade code mirror addons
- seperate folder upong different submodules (so that we can migrate to
- submodules for codemirror, shadereditor, glsl-optimzer)
- make shader editor independant of chrome extensions so that it's
  reusable otw. (as a vorlonjs plugin for isntance, for mobile shader
  remote debug)
- fixed a race condition (udpate a shader while it's being used.)
- added "theme" option
- added glsl preprocessor to clean uber shader to just what is used
- enabled new codemirror addons (mathhilight on word select, fold block
  or define block)
- added search documentation on main page (seems noboby knows how it
  works)

### CODE REVIEW

**Comment by Kuranes** [comment]
Altough it does work perfectly, It's more of a RFC than PR, as I didn't discuss it here before doing all the changes
You Might be interested in Ideas if not in implementations.

Questions/Notes:
- maybe need a "shader switcher" update block: only allow for editor shader switch once the shader is updated ? (still have bug if switching fast there)
- Usage of "inlet" rather than glslEditor https://github.com/patriciogonzalezvivo/glslEditor widgets is more lazyness than real UX thinking.  ( inlet give slider over those strange "2D" widget not sure, ideally perhaps show them all, and user choose what to use to edit his value). Notice the nice gifs documentating features easily
- debug breakpoint shader need some more work, CSS notably, but also UX (strange thing those + icons to be clicked)

Rationnale of new project folder/files:
- easier to understand, code and update 
- easier submodules update. 
- Code reuse of most of the code outside of a chrome extension

The Last point comes from the fact I did a working VorlonJS plugin (remote debug tool using websocket)  Perhaps that VorlonJS plugin could be a subfolder though. (debugging mobile shader is already an endless source of joy though ),

**Comment by spite** [comment]
Wow, these are a lot of changes! Thanks for all the hard work 👍 

I'm going to check them all one by one and reply to the ticket.

**Comment by Kuranes** [comment]
Thanks for taking the time, and I'm Sorry for the "big all at once PR" 

if you're interested in the vorlonjs plugin for remote debugging (think mobile)
https://dl.dropboxusercontent.com/u/2024901/shaderEditor.7z 
Once you installed vorlon, that would go into VorlonJS folder into Server\public\vorlon\plugins\shaderEditor 
( also need an entry into the config.json at vorlonjs root I think )

At least seeing the code from vorlonjs plugin would explain the folder/files changes, allowing one codebase to be shared efficiently on multiple plugin types (chrome / vorlonJS, and surely other websocket based remote code debug)

**Comment by Kuranes** [comment]
Might be interested in further check now rather than later, as according to twitter you're making new debug & remote debug tools. 

perfmeter/webvr could benefits from the "comm channels work" and thus work as remote debug tool on mobile using [vorlonjs](http://vorlonjs.com/) too, so that we can run them on gearVR for instance. (very painful to debug that one, as the "chrome android remote debug" flags is disabled, only vorlonjs works.

As said above,  could also lead to add your own websocket layers to handle message between client and remote, thus allowing you to do your own electron app as "server". 
(your own as opposed to vorlonjs one)

**Comment by spite** [comment]
I'm going to open different issues to discuss the different points :)

**Comment by Kuranes** [comment]
- repushed & updated with webgl2 support
(just overriding the webgl2renderingcontext too and sending a webglVersion parameter with the messages )
( direct version no install https://www.dropbox.com/s/rudwn4q2xjw5esb/shaderEditorExtension.7z?dl=0 )

**Comment by Kuranes** [comment]
@spite would it be ok if I publish it on chromewebstore?
 (needed for coworkers too lazy to install manually...) 

I let nearly all same description but for a "FORK" postfix and link as much as possible to the "official extension" (yours)

ps: tried the refactor commit by commit, but honelsty hard to get motivation on the chore. I'll finish the debug thingy and then will get back to it with hopefully more motivation...

**Comment by Kuranes** [comment]
@spite published here https://chrome.google.com/webstore/detail/a-shader-editor-fork/mnigdhbfgdodhbceojeikcpahlfccaof if you want to test debugger etc (it's unlisted in the store, just link shareable and you need to deactivate the previous shader editor)

**Comment by Kuranes** [comment]
@spite  fyi meanwhile three easy fixes that solved a lot of cases in my fork:
- `"run_at": "document_start"` in manfest.json https://github.com/Kuranes/ShaderEditorExtension-Fork/blob/feature/upgrade/src/manifest.json#L15 (Fixes webgl context not hooked early enough, which makes for instance shaderEditor code not having extension enabled on client side)
- handle shader webgl code that does `shaderAttach` then `shaderSource  `( ecmsrcipten did that, see sketchup link above) see https://github.com/Kuranes/ShaderEditorExtension-Fork/blob/feature/upgrade/src/WebGLHooks/client_webgl.js#L781-L849
- don't `updateProgram` on shaderEditor event `UpdateProgram`, just schedule/tag program, and update on next client Code `useProgram` (as it's easier to change program if already in webgl current "state"): https://github.com/Kuranes/ShaderEditorExtension-Fork/blob/feature/upgrade/src/WebGLHooks/client_webgl.js#L858-L860

**Pull request closed without merging**
