### PR TITLE
Make the tab unselectable and use default cursor

### PR DESCRIPTION
**Pull request by ebraminio**
Thank you for the great extension! It looks and works great and you did great job on developing it. Also thanks for releasing it as an opensource project! I did some minor improvements that I hope you like them.
- I thought the content of the tab should be unselectable like other inspector tabs, so I made body of the tab unselectable.
- On `/[ ]+main[ ]*\(/ig`, `i` matches incasesensitive but MaiN is not acceptable for shader programmes; also `g` matches multiple times which it doesn't seem multi `main` function make sense on a fragments shader so I've dropped these flags. `[ ]` matches only spaces but `\s` can match new lines in addition to spaces which would be useful on below cases:

```
void
main
() {
```

(splitting return type from function name by new line is not uncommon on C projects)
- Lastly I minified and prettified SVGs used but there is no any visual change on them AFAICS.

BTW I see program select color change is good enough, is there any specific case that this part fails?

Thank you again.

### CODE REVIEW

**Comment by spite** [comment]
Awesome job! Thanks!
A lot of this issues were in the back of my mind, thanks for taking care of them :)

About the program highlight, i disabled it because it was messing with the shaders. I think it's fixed in the next version I'm releasing.

Thanks again!

**Comment by ebraminio** [comment]
Thank you!!! Actually now I see the so weird issue raised by selecting second shader programme on webgl-water. I hope you can come around with some solution for it.

**Comment by spite** [comment]
Haha, that one is for a different reason. It actually works, but that shader calculates part of the water surface displacement map, and turning it magenta kicks the values into overdrive. That's part of the problem with messing with the shader output to highlight it: when it's used as a map, it can have destructive effects.

**Comment by ebraminio** [comment]
That one is causing [recoverable] kernel crashes and even BSOD sometimes for me that is why I thought it is most severe one :smiley:

**Pull request merged**
